sidesize=7;snakex=[];snakey=[];snakez=[];snakeangle=[];head=0;snakelength=+localStorage.snakelength||5;localStorage.snakelength=snakelength;playing=1;wrapenabled=lock=u=r=d=l=s=c=B=puzzling=0;emoji=[];stuck=0;pagename="";rot=0;move_scene=function(){scene.style.transform="translateX(-"+snakex[head]*sidesize+"vh)translateY(-"+snakey[head]*sidesize+"vh)translateZ(40vh)rotateX(40deg)rotateZ("+rot+"rad)"};
inithtml=function(a){pagename=a;document.body.outerHTML='<title>SNAKE</title>\n<body id=b class="'+a+'">\n<div id=perspective>\n  <div id=scene style="transform:translateX(-92vh)translateY(-109vh)rotateZ(90deg)translateZ(79vh);transform-origin:99vh 99vh">\n    <div id=objects></div>\n    <div id=snake></div>\n  </div>\n</div>\n<div style="position:fixed;bottom:5px;left:5px;width:200px">\n  <button onclick="rot+=Math.PI/4;move_scene()">\u21bb</button>\n  <button onclick="rot-=Math.PI/4;move_scene()">\u21ba</button>\n  <button onclick="localStorage.clear()">clear</button>\n</div>'};
drawobjects=function(){for(i in emojis){var a={b:"\ud83c\udf33",a:"\ud83c\udf4e"}[emojis[i][2]];objects.innerHTML+="<div id=emoji"+i+' class="emoji '+emojis[i][2]+'" style="left:'+emojis[i][0]*sidesize+"vh;top:"+emojis[i][1]*sidesize+'vh">'+a+"</div><div id=emojishadow"+i+' class="emojishadow '+emojis[i][2]+'shadow" style="left:'+emojis[i][0]*sidesize+"vh;top:"+emojis[i][1]*sidesize+'vh">'+a}for(i in doors)objects.innerHTML+="<div id=door"+i+' class="door'+(doors[i][5]?" open":"")+'" style="left:'+
doors[i][0]*sidesize+"vh;top:"+doors[i][1]*sidesize+"vh;transform:rotateZ("+doors[i][2]+'rad)translateZ(-1vh)"><div class=path></div><div class=realdoor '+(doors[i][7]?"":"hidden")+">"+(doors[i][3]||"")};
resetsnake=function(a){snake.innerHTML="";a||(snakex=[],snakey=[],snakez=[],snakeangle=[]);top.size&&(sidesize=32/size);head=snakelength-1;if(!a)if("editor"==b.className)for(i=0;i<snakelength;i++)snakex[head-i]=-i,snakey[head-i]=~~(size/2),snakez[head-i]=0,snakeangle[head-i]=-Math.PI/2;else if(localStorage.snakex){a=+localStorage.snakex;var f=+localStorage.snakey,g=+localStorage.snakez,e=parseFloat(localStorage.snakeangle);if(2>a)for(i=0;i<snakelength;i++)snakex[head-i]=a-i,snakey[head-i]=f,snakez[head-
i]=g,snakeangle[head-i]=e;else if(28<a)for(i=0;i<snakelength;i++)snakex[head-i]=a+i,snakey[head-i]=f,snakez[head-i]=g,snakeangle[head-i]=e}else if("hub"==b.className)for(i=0;i<snakelength;i++)snakex[head-i]=15,snakey[head-i]=15,snakez[head-i]=-i-1,snakeangle[head-i]=0;for(i=0;i<Math.max(snakelength,16);i++)snake.innerHTML+="<div id=snakecubemove"+i+' class=snakecubemove style="transform:translateX(50vh)translateY(50vh)translateZ(-10vh);width:'+(sidesize-1)+"vh;height:"+(sidesize-1)+'vh"><div class=snakeshadow id=snakeshadow'+
i+"></div><div id=snakecuberotate"+i+' class=snakecuberotate><div class="cube snake" id=snakecube'+i+">"+(1>i?"<div class=tongue>Y</div>":"")+"<div class=front>"+(1>i?"\u203f":"")+'</div><div class=up style="font-size:'+.5*sidesize+"vh;line-height:"+.8*sidesize+'vh">'+(1>i?"\ud83d\udc40":"")+"</div><div class=right></div><div class=left></div><div class=back></div><div class=down>"};
movesnake=function(){for(i=0;i<snakelength;i++){var a=oldx=oldy=oldz=newx=newy=newz=0;wrapenabled&&(0==snakex[head-i-1]&&snakex[head-i]==size-1&&(a=1,oldx=-1,newx=size,oldy=newy=snakey[head-i],oldz=newz=snakez[head-i]),snakex[head-i-1]==size-1&&0==snakex[head-i]&&(a=1,oldx=size,newx=-1,oldy=newy=snakey[head-i],oldz=newz=snakez[head-i]),0==snakey[head-i-1]&&snakey[head-i]==size-1&&(a=1,oldy=-1,newy=size,oldx=newx=snakex[head-i],oldz=newz=snakez[head-i]),snakey[head-i-1]==size-1&&0==snakey[head-i]&&
(a=1,oldy=size,newy=-1,oldx=newx=snakex[head-i],oldz=newz=snakez[head-i]),0==snakez[head-i-1]&&snakez[head-i]==size-1&&(a=1,oldz=-1,newz=size,oldx=newx=snakex[head-i],oldy=newy=snakey[head-i]),snakez[head-i-1]==size-1&&0==snakez[head-i]&&(a=1,oldz=size,newz=-1,oldx=newx=snakex[head-i],oldy=newy=snakey[head-i]));a?(top["snakecuberotate"+i].style.transform="rotateZ("+snakeangle[head-i]+"rad)",top["snakecubemove"+i].style.transform="translateX("+(oldx*sidesize+.5)+"vh)translateY("+(oldy*sidesize+.5)+
"vh)translateZ("+(oldz*sidesize+.5)+"vh)scale(.01)scaleZ(.01)",setTimeout("snakecubemove"+i+".style.transition='none'",150),setTimeout("snakecubemove"+i+".style.transform=`translateX(${"+newx+"*sidesize+.5}vh)translateY(${"+newy+"*sidesize+.5}vh)translateZ(${"+newz+"*sidesize+.5}vh)scale(.01)`",175),setTimeout("snakecubemove"+i+".style.transition='';snakecubemove"+i+".style.transform=`translateX(${snakex["+(head-i)+"]*sidesize+.5}vh)translateY(${snakey["+(head-i)+"]*sidesize+.5}vh)translateZ(${snakez["+
(head-i)+"]*sidesize+.5}vh)`",200)):(top["snakecubemove"+i].style.transform="translateX("+(snakex[head-i]*sidesize+.5)+"vh)translateY("+(snakey[head-i]*sidesize+.5)+"vh)translateZ("+(snakez[head-i]*sidesize+.9)+"vh)",top["snakecuberotate"+i].style.transform="rotateZ("+snakeangle[head-i]+"rad)");top["snakeshadow"+i].style.display=0==snakez[head-i]?"":"none";if("hub"==b.className||"hub2"==b.className)scene.style.transform="translateX("+-snakex[head]*sidesize+"vh)translateY("+-snakey[head]*sidesize+
"vh)translateZ(20vh)rotateX(40deg)",scene.style.transformOrigin=""+snakex[head]*sidesize+"vh "+snakey[head]*sidesize+"vh"}for(i=snakelength;16>i;i++)top["snakecubemove"+i].style.transform="translateX("+(snakex[head-snakelength]*sidesize+.5)+"vh)translateY("+(snakey[head-snakelength]*sidesize+.5)+"vh)translateZ("+-100*sidesize+"vh)"};
checkmove=function(a,f,g){"editor playing"==b.className&&(-5>a||a>size+3||-2>f||f>size)&&(stuck=1);if("hub"==b.className||"hub2"==b.className)if(0>a||29<a||0>f||29<f)stuck=1;for(var e in emojis)a==emojis[e][0]&&f==emojis[e][1]&&("apple"==emojis[e][2]?(delete emojis[e],top["emoji"+e].remove(),top["emojishadow"+e].remove(),snakelength++,localStorage.snakelength=snakelength):stuck=1);for(e in doors)0<doors[e][3]&&snakelength>=doors[e][3]&&4>Math.hypot(a-doors[e][0],f-doors[e][1])&&(top["door"+e].className=
"door open",localStorage["door"+pagename+e]=1),"door open"==top["door"+e].className&&2>Math.hypot(a-doors[e][0],f-doors[e][1])&&(stuck=0,setTimeout("location='"+doors[e][6]+".html'",1E3),localStorage.snakex=doors[e][8],localStorage.snakey=doors[e][9],localStorage.snakez=0,localStorage.snakeangle=snakeangle[head]);for(e=snakelength-2;0<e;e--)snakex[head-e]==a&&snakey[head-e]==f&&snakez[head-e]==g&&(stuck=1)};
checkgrid=function(){solved=1;for(i=0;i<size;i++)for(j=0;j<size;j++)top["g"+i+j].style.background=dg[i][j]?"black":"white",top["w"+i+j].style.background=dw[i][j]?"black":"white";for(i=0;i<snakelength;i++){try{top["g"+snakey[head-i]+snakex[head-i]].style.background=dg[snakey[head-i]][snakex[head-i]]?"green":"red",top["w"+(size-1-snakez[head-i])+snakex[head-i]].style.background=dw[size-1-snakez[head-i]][snakex[head-i]]?"green":"red"}catch(a){}if(0>snakex[head-i]||snakex[head-i]>size-1||0>snakey[head-
i]||snakey[head-i]>size-1||0>snakez[head-i]||snakez[head-i]>size-1)solved=0;ground.checked&&dg[snakey[head-i]]&&!dg[snakey[head-i]][snakex[head-i]]&&(solved=0);wall.checked&&dw[size-1-snakez[head-i]]&&!dw[size-1-snakez[head-i]][snakex[head-i]]&&(solved=0)}for(i=0;i<size;i++)for(j=0;j<size;j++)ground.checked&&"black"==top["g"+i+j].style.backgroundColor&&(solved=0),wall.checked&&"black"==top["w"+i+j].style.backgroundColor&&(solved=0);solved&&setTimeout('alert("SOLVED")',300)};
onkeydown=function(a){top["lurd************************l**r************l*d***u**u"[a.which-37]]=1;if(8==a.which||18==a.which)B=1;16==a.which&&(s=1);17==a.which&&(c=1);116!=a.keyCode&&82!=a.keyCode&&17!=a.keyCode&&123!=a.keyCode&&a.preventDefault();a=0;playing&&puzzling&&0<=snakex[head]&&snakex[head]<size&&0<=snakey[head]&&snakey[head]<size&&0<=snakez[head]&&snakez[head]<size&&(a=1);playing&&!lock&&(stuck=0,l?top.wrap&&wrap.checked&&a&&0==snakex[head]?(checkmove(size-1,snakey[head],snakez[head]),stuck||
(snakex.push(size-1),snakey.push(snakey[head]),snakez.push(snakez[head]),snakeangle.push(Math.PI/2),head++)):(checkmove(snakex[head]-1,snakey[head],snakez[head]),stuck||(snakex.push(snakex[head]-1),snakey.push(snakey[head]),snakez.push(snakez[head]),snakeangle.push(Math.PI/2),head++)):r?top.wrap&&wrap.checked&&a&&snakex[head]==size-1?(checkmove(0,snakey[head],snakez[head]),stuck||(snakex.push(0),snakey.push(snakey[head]),snakez.push(snakez[head]),snakeangle.push(-Math.PI/2),head++)):(checkmove(snakex[head]+
1,snakey[head],snakez[head]),stuck||(snakex.push(snakex[head]+1),snakey.push(snakey[head]),snakez.push(snakez[head]),snakeangle.push(-Math.PI/2),head++)):u?top.wrap&&wrap.checked&&a&&0==snakey[head]?(checkmove(snakex[head],size-1,snakez[head]),stuck||(snakex.push(snakex[head]),snakey.push(size-1),snakez.push(snakez[head]),snakeangle.push(Math.PI),head++)):(checkmove(snakex[head],snakey[head]-1,snakez[head]),stuck||(snakex.push(snakex[head]),snakey.push(snakey[head]-1),snakez.push(snakez[head]),snakeangle.push(Math.PI),
head++)):d?top.wrap&&wrap.checked&&a&&snakey[head]==size-1?(checkmove(snakex[head],0,snakez[head]),stuck||(snakex.push(snakex[head]),snakey.push(0),snakez.push(snakez[head]),snakeangle.push(0),head++)):(checkmove(snakex[head],snakey[head]+1,snakez[head]),stuck||(snakex.push(snakex[head]),snakey.push(snakey[head]+1),snakez.push(snakez[head]),snakeangle.push(0),head++)):top.wall&&wall.checked&&s?top.wrap&&wrap.checked&&a&&snakez[head]==size-1?(checkmove(snakex[head],snakey[head],0),stuck||(snakex.push(snakex[head]),
snakey.push(snakey[head]),snakez.push(0),snakeangle.push(snakeangle[head]),head++)):(checkmove(snakex[head],snakey[head],snakez[head]+1),stuck||(snakex.push(snakex[head]),snakey.push(snakey[head]),snakez.push(snakez[head]+1),snakeangle.push(snakeangle[head]),head++)):top.wall&&wall.checked&&c?top.wrap&&wrap.checked&&a&&0==snakez[head]?(checkmove(snakex[head],snakey[head],size-1),stuck||(snakex.push(snakex[head]),snakey.push(snakey[head]),snakez.push(size-1),snakeangle.push(snakeangle[head]),head++)):
0==snakez[head]?stuck=1:(checkmove(snakex[head],snakey[head],snakez[head]-1),stuck||(snakex.push(snakex[head]),snakey.push(snakey[head]),snakez.push(snakez[head]-1),snakeangle.push(snakeangle[head]),head++)):B&&head>snakelength&&(snakeangle.pop(),snakex.pop(),snakey.pop(),snakez.pop(),head--),!stuck&&(u||r||d||l||s||c||B)&&(movesnake(),"editor playing"==b.className&&checkgrid(),lock=1,setTimeout("lock=0",100)))};onkeyup=function(){u=r=d=l=s=c=B=0};
onload=function(){inithtml("hub");debug=1;emojis=[[24,22,"tree"],[7,7,"tree"],[9,6,"apple"],[5,8,"apple"],[22,22,"apple"]];doors=[[31,15,Math.PI/2,5,0,0,8,1,0,15],[15,-1,0,16,0,0,16,1,0,0]];drawobjects();localStorage.snakex?(scene.style.transition=".8s",resetsnake(),movesnake()):debug?(scene.style.transition=".8s",resetsnake(),movesnake(),snakex.push(snakex[head]),snakey.push(snakey[head]),snakez.push(0),snakeangle.push(snakeangle[head]),head++,movesnake()):(lock=1,setTimeout('resetsnake();movesnake();snakecubemove0.style.transition=".5s"',
2E3),setTimeout("snakex.push(snakex[head]);snakey.push(snakey[head]);snakez.push(0);snakeangle.push(snakeangle[head]);head++;movesnake()",6E3),setTimeout("snakecubemove0.style.transition='';snakeshadow0.style.transition=snakecuberotate0.style.transition='.2s';snakeshadow0.style.transform=snakecuberotate0.style.transform='rotateZ("+-Math.PI/4+"rad)'",6500),setTimeout("snakeshadow0.style.transform=snakecuberotate0.style.transform='rotateZ("+Math.PI/4+"rad)'",7E3),setTimeout("snakeshadow0.style.transform=snakecuberotate0.style.transform='';",
7500),setTimeout("scene.style.transition='.8s';snakeshadow0.style.transition=snakecuberotate0.style.transition='';lock=0",9E3))};nload=function(){inithtml("hub2");emojis=[];doors=[[-1,15,-Math.PI/2,8,0,1,"index",0,29,15]];drawobjects();debug=1;scene.style.transition=".8s";resetsnake();movesnake()};
load=function(){gridsize.value=snakesize.value=5;ground.checked=!0;wall.checked=!1;wrap.checked=!1;ground.onclick=function(){0==ground.checked&&(wall.checked=!0)};wall.onclick=function(){0==wall.checked&&(ground.checked=!0)};wrap.onclick=function(){wrapenabled=wrap.checked};dw=[];dg=[];snakesize.onchange=snakesize.oninput=function(){snakeval.innerHTML=snakelength=+snakesize.value;resetsnake()};size=5;reset.onclick=gridsize.onchange=gridsize.oninput=resizegrid=function(){gridval.innerHTML=size=+gridsize.value;
var a=100/size;down.innerHTML="";ghtml=whtml=back.innerHTML="";dw=[];dg=[];for(i=0;i<size;i++)for(dw[i]=[],dg[i]=[],j=0;j<size;j++)dw[i][j]=0,dg[i][j]=0;for(i=0;i<size;i++)for(j=0;j<size;j++)whtml+="<div class=cell id=w"+i+j+" style='width:"+a+"%;padding-top:"+a+"%' onmousedown='paint("+i+","+j+",this,0)' onmousemove='paint("+i+","+j+",this,0,1)'></div>",ghtml+="<div class=cell id=g"+i+j+" style='width:"+a+"%;padding-top:"+a+"%' onmousedown='paint("+i+","+j+",this,1)' onmousemove='paint("+i+","+j+
",this,1,1)'></div>";down.innerHTML+=ghtml;back.innerHTML+=whtml;resetsnake();movesnake()};resizegrid();paint=function(a,f,g,e,h){playing||(e=e?dg:dw,h&&mousedown&&(e[a][f]=1),h||(e[a][f]^=1),g.style.background=e[a][f]?"#000":"#fff")};print=function(a){var f="";for(i in a)for(j in a[i])f+=a[i][j];return f};share.onclick=function(){var a=[];a.push(size);a.push(snakesize.value);a.push(wrap.checked?1:0);a.push(wall.checked?print(dw):"");a.push(ground.checked?print(dg):"");prompt("Share this link:",location+
"#"+a)};mousedown=0;onmousedown=function(){mousedown=1};onmouseup=function(){mousedown=0};ondragstart=function(a){a.preventDefault()};playing=puzzling=0;test.onclick=function(){playing=puzzling=1;b.className="editor playing"};quit.onclick=function(){playing?(playing=puzzling=0,b.className="editor",resetsnake(),checkgrid()):location="index.html"};move_scene=function(){scene.style.transform="rotateX(38deg)translateX(-18vh)rotateZ("+rot+"rad)"};move_scene()};